name: oxid package tests

on: [push]

jobs:
  stand_alone_checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Validate composer.json
      run: composer validate
    - name: install composer dependencies
      run: composer install
    - name: lint php files
      run: composer lint
    - name: check codestyle
      run: composer codestyle
